# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kadnums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadnum', models.CharField(max_length=22)),
                ('zona', models.CharField(max_length=2)),
                ('kvartal', models.CharField(max_length=3)),
                ('parcel', models.CharField(max_length=4)),
                ('purpose', models.CharField(max_length=5)),
                ('unit_area', models.CharField(max_length=20)),
                ('area', models.FloatField()),
                ('ownershipcode', models.CharField(max_length=6)),
                ('id_office', models.CharField(max_length=6)),
                ('koatuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadastr.ikk')),
            ],
        ),
    ]
