# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr', '0002_kadnums'),
    ]

    operations = [
        migrations.CreateModel(
            name='kad_ext_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_xmax', models.FloatField()),
                ('st_ymax', models.FloatField()),
                ('st_xmin', models.FloatField()),
                ('st_ymin', models.FloatField()),
                ('cadnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadastr.kadnums')),
            ],
        ),
    ]
