# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr', '0003_kad_ext_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='przem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=5)),
                ('przem', models.TextField()),
            ],
        ),
    ]
