# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr', '0004_przem'),
    ]

    operations = [
        migrations.AddField(
            model_name='przem',
            name='type_dzk',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
