# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr', '0006_fromdzk'),
    ]

    operations = [
        migrations.CreateModel(
            name='kvartal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvartal', models.IntegerField(max_length=3)),
                ('koatuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadastr.ikk')),
            ],
        ),
        migrations.CreateModel(
            name='zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.IntegerField(max_length=2)),
                ('koatuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadastr.ikk')),
            ],
        ),
        migrations.RenameField(
            model_name='kadnums',
            old_name='purpose',
            new_name='use',
        ),
        migrations.RemoveField(
            model_name='fromdzk',
            name='purpose',
        ),
        migrations.AddField(
            model_name='fromdzk',
            name='use',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kvartal',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadastr.zona'),
        ),
    ]
