# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr', '0007_auto_20151226_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvartal',
            name='kvartal',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='zona',
            name='zona',
            field=models.CharField(max_length=2),
        ),
    ]
